import { requestExpandedMode } from "@devvit/web/client";
import { incrementDailyCountOnce } from "../lib/dailyCount";

const memesCountEl = document.getElementById("memes-count") as HTMLSpanElement | null;
const versionEl = document.getElementById("app-version") as HTMLSpanElement | null;
const collageEl = document.querySelector(".collage");
// Splash screen logic
console.log("Splash loaded");

const startButton = document.getElementById(
  "start-button"
) as HTMLButtonElement;

startButton.addEventListener("click", (e) => {
  requestExpandedMode(e, "game");
});

// Daily counter (shared with in-app gallery) to keep mobile/desktop consistent
if (memesCountEl) {
  incrementDailyCountOnce()
    .then((count) => {
      memesCountEl.textContent = count.toString();
    })
    .catch(() => {
      // leave default content on failure
    });
}

// Show build/dev version (generated by predev script)
if (versionEl) {
  fetch("/version.json")
    .then((res) => (res.ok ? res.json() : { version: "dev" }))
    .then((data) => {
      if (data?.version) {
        versionEl.textContent = `v${data.version}`;
      }
    })
    .catch(() => {
      versionEl.textContent = "vdev";
    });
}

// Build a 10x10 background grid of meme tiles (decorative, no tab focus)
if (collageEl instanceof HTMLElement) {
  const templates = [
    { src: "/distracted-boyfriend.jpg", alt: "Distracted boyfriend" },
    { src: "/drake.jpg", alt: "Drake hotline bling" },
    { src: "/astronauts.jpg", alt: "Astronauts" },
    { src: "/toy-story.jpg", alt: "Toy Story" },
    { src: "/uno-draw-25.jpg", alt: "Uno draw 25" },
    { src: "/batman-slap.jpg", alt: "Batman slap" },
    { src: "/buttons.jpg", alt: "Buttons" },
    { src: "/left-exit.jpg", alt: "Left exit" },
    { src: "/waiting-skeleton.jpg", alt: "Waiting skeleton" },
    { src: "/roll-safe-think-about-it.jpg", alt: "Roll Safe" },
    { src: "/this-is-fine.jpg", alt: "This is fine" },
    { src: "/monkey-puppet.jpg", alt: "Awkward monkey" },
    { src: "/change-my-mind.jpg", alt: "Change my mind" },
    { src: "/laughing-leo.webp", alt: "Laughing Leo" },
    { src: "/yall-got-any-more-of-that.jpg", alt: "Yall got any more" },
    { src: "/padme-anakin.jpg", alt: "Padme Anakin" },
  ];

  const totalTiles = 150; // enough to fill auto-fit grid across widths

  for (let i = 0; i < totalTiles; i++) {
    const t = templates[i % templates.length]!;
    const tile = document.createElement("div");
    tile.className = "strip-card";
    tile.setAttribute("aria-hidden", "true");

    const img = document.createElement("img");
    img.src = t.src;
    img.alt = "";
    img.loading = "lazy";

    tile.appendChild(img);
    collageEl.appendChild(tile);
  }
}
